# Stage 1
FROM node:latest as build
WORKDIR /app

COPY . .

RUN npm i

RUN npm run build

# Stage 2
FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
