FROM node:latest as build

WORKDIR /app

COPY package.json ./

RUN npm install --silent

COPY . .

RUN npm run build

# Etapa de producción
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

