version: "3.9"

services:
  database:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - production
    
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: page
    restart: always
    # Expose frontend on port 80 for Nginx
    ports:
      - "80:80"
    depends_on:
      - rag
      - crud
    networks:
      - production

  rag:
    build:
      context: ./backend/api_rag
      dockerfile: Dockerfile.prod
    container_name: api_rag
    restart: always
    # No need to expose ports for backend in production
    # ports:
    #   - "5000:5000"
    networks:
      - production
 
  crud:
    build:
      context: ./backend/api_crud
      dockerfile: Dockerfile.prod
    container_name: api_crud
    restart: always
    # No need to expose ports for backend in production
    # ports:
    #   - "3000:3000"
    links:
      - database
    networks:
      - production
 
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    # Link frontend service to Nginx
    depends_on:
      - frontend
    networks:
      - production

networks:
  production:

volumes:
  mongo-data:
