services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - development

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    restart: always
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma/
    networks:
      - development

  flask:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/usr/src/app
    networks:
      - development

  vite:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: vite
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - development

networks:
  development:

volumes:
  mongo-data:
  chroma-data:
