services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-data:/data/db
    networks:
      - production

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    restart: always
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    networks:
      - production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    restart: always
    environment:
      - FLASK_ENV=production
    networks:
      - production

  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - production

networks:
  production:

volumes:
  mongo-data:
  chroma-data:

