version: "3.9"

services:
  #database:
  #  image: mongo
  #  container_name: mongo
  #  restart: always
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  ports:
  #    - "27017:27017"
  #  volumes:
  #    - mongo-data:/data/db


  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - development

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: react
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - development

networks:
  development:

volumes:
#  mongo-data:
  node_modules:
